// ESLint Config
//
// Purpose: strictTypeChecked ESLint config with phased-warn strategy
// See: https://pocketarc.com/typescript

import eslint from "@eslint/js";
import tseslint from "typescript-eslint";
import eslintSecurity from "eslint-plugin-security";

export default tseslint.config(
  eslint.configs.recommended,
  eslintSecurity.configs.recommended,
  {
    rules: {
      // Known false-positive for client-side apps — config[key] is data access, not injection
      "security/detect-object-injection": "off",
    },
  },
  ...tseslint.configs.strictTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: {
          allowDefaultProject: [
            // Source files not statically reachable from any tsconfig root:
            // dynamically loaded modules, standalone entry points, orphan barrels.
            // tsconfig.json only extends tsconfig_editor, so projectService never
            // loads tsconfig_player/tsconfig_synth; these fall back to the default
            // project (tsconfig.json) for type info.
            "editor/generated-ui/change-factory.ts",
            "editor/generated-ui/panel-factory.ts",
            "editor/core/tag-autocomplete.ts",
            "player/main.ts",
            "player/player-controls.ts",
            "player/player-keyboard.ts",
            "synth/synthesis/index.ts",
            "synth/socket/external-loader.ts",
            "synth/socket/external-manifest.ts",
            "synth/socket/legacy-importer.ts",
            "synth/socket/url-varint.ts",
            "synth/formats/jukebox-exp-v2.ts",
            "synth/render/worklet.ts",
            "synth/render/worklet-synth.ts",
            "synth/modules/drumset/serde.ts",
            "synth/modules/mod/serde.ts",
            // Test files (not scanned by scripts/lint.sh; listed for manual eslint runs)
            "tests/navigator-contracts.test.ts",
            "tests/css-var-contract.test.ts",
            "tests/interactions-behavior.test.ts",
            "tests/loop-editor-contract.test.ts",
            "tests/song-document-contract.test.ts",
            "tests/style-inject.test.ts",
            "tests/style-slots.test.ts",
            "tests/dom-hooks.test.ts",
            "tests/prompt-shell-contract.test.ts",
            "tests/svg-editor-rect-contract.test.ts",
            "tests/svg-prompt-transaction-contract.test.ts",
            "tests/synth-contract.test.ts",
            "tests/ui-states.test.ts",
            "tests/socket-contract.test.ts",
            "tests/modules-supersaw.test.ts",
            "tests/plugin-round-trip.test.ts",
            "tests/synth-utilities.test.ts",
            "tests/generated-ui.test.ts",
            "tests/serde-container.test.ts",
            "tests/legacy-importer.test.ts",
            "tests/placeholder-module.test.ts",
            "tests/url-varint.test.ts",
            "tests/modules-pulse.test.ts",
            "tests/modules-noise.test.ts",
            "tests/modules-custom-chip-wave.test.ts",
            "tests/modules-chip.test.ts",
            "tests/modules-harmonics.test.ts",
            "tests/modules-spectrum.test.ts",
            "tests/modules-picked-string.test.ts",
            "tests/modules-fm.test.ts",
            "tests/modules-fm6.test.ts",
            "tests/modules-drumset.test.ts",
            "tests/module-deletion.test.ts",
            "tests/modules-mod.test.ts",
            "tests/barrel-exports.test.ts",
            "tests/player-ui-styles.test.ts",
            "tests/editor-selector-scope.test.ts",
            "tests/website-html-contract.test.ts",
            "tests/capability-lookup.test.ts",
            "tests/instrument-tagging.test.ts",
            "tests/external-loader.test.ts",
            "tests/effect-state.test.ts",
            "tests/song-serialization.test.ts",
            "tests/fixtures/community-x-wt.ts",
            "tests/fixtures/community-missing-schema.ts",
            "tests/fixtures/community-missing-serialize.ts",
            "tests/fixtures/community-missing-deserialize.ts",
            "community_modules/simple_synth/module.ts",
            "community_modules/simple_synth/schema.ts",
            "community_modules/simple_synth/serde.ts",
            "community_modules/simple_synth/dsp.ts",
            "tests/examples/community-simple-synth.test.ts",
            "eslint.config.mjs",
          ],
          maximumDefaultProjectFileMatchCount_THIS_WILL_SLOW_DOWN_LINTING: 30,
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    ignores: [
      "build/**",
      "website/**",
      "archive/**",
      "node_modules/**",
      "conventions/**",
      ".kilocode/**",
      // Generated by wasm-pack (build-wasm.sh); not hand-edited source
      "synth/wasm-synth/pkg/**",
      // Not tracked by any tsconfig
      "editor/config/index.ts",
      "editor/core/index.ts",
      "editor/input/**",
      "editor/io/index.ts",
      "editor/prompts/index.ts",
      "editor/renderers/index.ts",
      "editor/rendering/index.ts",
      "player/index.ts",
    ],
  },
  {
    rules: {
      // ── Error-level (block CI) ──

      "no-var": "error",
      "no-empty": ["warn", { allowEmptyCatch: true }],

      // Low-volume, high-value type-safety rules — keep as errors
      "@typescript-eslint/no-duplicate-type-constituents": "error",
      "@typescript-eslint/no-redundant-type-constituents": "error",
      "@typescript-eslint/no-misused-promises": ["error", {
        "checksVoidReturn": false
      }],
      "@typescript-eslint/no-useless-constructor": "error",
      "@typescript-eslint/no-duplicate-enum-values": "error",
      "@typescript-eslint/no-unnecessary-type-parameters": "error",
      "@typescript-eslint/no-base-to-string": "warn",

      // ── Fix-immediately warn (target: migrate to error) ──

      "eqeqeq": "warn",
      "@typescript-eslint/no-deprecated": "warn",
      "@typescript-eslint/ban-ts-comment": "warn",
      "@typescript-eslint/no-unsafe-function-type": "warn",
      "@typescript-eslint/no-floating-promises": "warn",
      "no-irregular-whitespace": "warn",
      "@typescript-eslint/no-implied-eval": "warn",
      "@typescript-eslint/no-extraneous-class": "warn",

      // ── Structural warns (DOM codebase — inherently unsafe-typed) ──

      "@typescript-eslint/no-unsafe-assignment": "warn",
      "@typescript-eslint/no-unsafe-member-access": "warn",
      "@typescript-eslint/no-unsafe-call": "warn",
      "@typescript-eslint/no-unsafe-return": "warn",
      "@typescript-eslint/no-unsafe-argument": "warn",
      "@typescript-eslint/no-unsafe-enum-comparison": "warn",
      "@typescript-eslint/restrict-plus-operands": "warn",
      "@typescript-eslint/restrict-template-expressions": "warn",

      // ── High-volume but fixable over time ──

      "@typescript-eslint/no-non-null-assertion": "warn",
      "@typescript-eslint/no-confusing-void-expression": "warn",
      "@typescript-eslint/no-unnecessary-condition": "warn",
      "@typescript-eslint/no-unnecessary-type-assertion": "warn",
      "@typescript-eslint/no-unnecessary-boolean-literal-compare": "warn",
      "@typescript-eslint/no-unnecessary-type-conversion": "warn",
      "@typescript-eslint/no-unnecessary-template-expression": "warn",
      "@typescript-eslint/unbound-method": "warn",
      "@typescript-eslint/prefer-literal-enum-member": "warn",
      "@typescript-eslint/use-unknown-in-catch-callback-variable": "warn",

      // ── Legacy relaxations ──

      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-this-alias": "off",
      "@typescript-eslint/no-unused-expressions": "off",
      "no-constant-condition": "off",
      "no-prototype-builtins": "off",
      "no-useless-assignment": "warn",
      "prefer-const": "warn",
    },
  },
  {
    // Serialization layer exemption — operates on untyped JSON (Record<string, unknown>)
    files: ["synth/song-serialization.ts", "synth/formats/legacy-compat.ts", "synth/formats/jukebox-exp.ts"],
    rules: {
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-return": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-deprecated": "off",
    },
  },
  {
    // MIDI parser tracks held notes in a Record keyed by pitch; `delete` on a
    // computed key is the idiomatic cleanup. no-dynamic-delete is a false positive here.
    files: ["editor/io/midi-parser.ts"],
    rules: {
      "@typescript-eslint/no-dynamic-delete": "off",
    },
  },
);
