// css-var-contract.ts
//
// Purpose: Single source of truth for CSS custom properties used by themes, shared styles, editor, and player

export const themeCoreCssVars = [
	"--black-piano-key",
	"--black-piano-key-text",
	"--box-selection-fill",
	"--disabled-note-primary",
	"--disabled-note-secondary",
	"--editor-background",
	"--hout",
	"--hover-preview",
	"--indicator-primary",
	"--indicator-secondary",
	"--inverted-text",
	"--link-accent",
	"--loop-accent",
	"--multiplicative-mod-slider",
	"--mute-button-mod",
	"--mute-button-normal",
	"--note-flash",
	"--note-flash-secondary",
	"--overwriting-mod-slider",
	"--page-margin",
	"--playhead",
	"--primary-text",
	"--progress-bar",
	"--scrollbar-background",
	"--scrollbar-color",
	"--secondary-text",
	"--select2-opt-group",
	"--settings-header-text",
	"--song-player-margin",
	"--spectrum-line-L",
	"--spectrum-line-R",
	"--text-disabled-icon",
	"--text-enabled-icon",
	"--text-selection",
	"--text-spacing-icon",
	"--track-editor-bg-mod",
	"--track-editor-bg-mod-dim",
	"--track-editor-bg-noise",
	"--track-editor-bg-noise-dim",
	"--track-editor-bg-pitch",
	"--track-editor-bg-pitch-dim",
	"--ui-widget-background",
	"--ui-widget-focus",
	"--white-piano-key",
	"--white-piano-key-text",
] as const;

export const channelColorCssVars = [
	"--fifth-note",
	"--formula-mod-channel-limit",
	"--formula-noise-channel-limit",
	"--formula-pitch-channel-limit",
	"--mod-channel-limit",
	"--mod-color",
	"--mod-key-symbol",
	"--mod-label-primary",
	"--mod-label-primary-text",
	"--mod-label-secondary-text",
	"--mod-position",
	"--mod-primary-channel-hue",
	"--mod-primary-channel-hue-scale",
	"--mod-primary-channel-lum",
	"--mod-primary-channel-lum-scale",
	"--mod-primary-channel-sat",
	"--mod-primary-channel-sat-scale",
	"--mod-primary-note-hue",
	"--mod-primary-note-hue-scale",
	"--mod-primary-note-lum",
	"--mod-primary-note-lum-scale",
	"--mod-primary-note-sat",
	"--mod-primary-note-sat-scale",
	"--mod-secondary-channel-hue",
	"--mod-secondary-channel-hue-scale",
	"--mod-secondary-channel-lum",
	"--mod-secondary-channel-lum-scale",
	"--mod-secondary-channel-sat",
	"--mod-secondary-channel-sat-scale",
	"--mod-secondary-note-hue",
	"--mod-secondary-note-hue-scale",
	"--mod-secondary-note-lum",
	"--mod-secondary-note-lum-scale",
	"--mod-secondary-note-sat",
	"--mod-secondary-note-sat-scale",
	"--mod-title",
	"--mod1-primary-channel",
	"--mod1-primary-note",
	"--mod1-secondary-channel",
	"--mod1-secondary-note",
	"--mod2-primary-channel",
	"--mod2-primary-note",
	"--mod2-secondary-channel",
	"--mod2-secondary-note",
	"--mod3-primary-channel",
	"--mod3-primary-note",
	"--mod3-secondary-channel",
	"--mod3-secondary-note",
	"--mod4-primary-channel",
	"--mod4-primary-note",
	"--mod4-secondary-channel",
	"--mod4-secondary-note",
	"--noise-channel-limit",
	"--noise-primary-channel-hue",
	"--noise-primary-channel-hue-scale",
	"--noise-primary-channel-lum",
	"--noise-primary-channel-lum-scale",
	"--noise-primary-channel-sat",
	"--noise-primary-channel-sat-scale",
	"--noise-primary-note-hue",
	"--noise-primary-note-hue-scale",
	"--noise-primary-note-lum",
	"--noise-primary-note-lum-scale",
	"--noise-primary-note-sat",
	"--noise-primary-note-sat-scale",
	"--noise-secondary-channel-hue",
	"--noise-secondary-channel-hue-scale",
	"--noise-secondary-channel-lum",
	"--noise-secondary-channel-lum-scale",
	"--noise-secondary-channel-sat",
	"--noise-secondary-channel-sat-scale",
	"--noise-secondary-note-hue",
	"--noise-secondary-note-hue-scale",
	"--noise-secondary-note-lum",
	"--noise-secondary-note-lum-scale",
	"--noise-secondary-note-sat",
	"--noise-secondary-note-sat-scale",
	"--noise1-primary-channel",
	"--noise1-primary-note",
	"--noise1-secondary-channel",
	"--noise1-secondary-note",
	"--noise2-primary-channel",
	"--noise2-primary-note",
	"--noise2-secondary-channel",
	"--noise2-secondary-note",
	"--noise3-primary-channel",
	"--noise3-primary-note",
	"--noise3-secondary-channel",
	"--noise3-secondary-note",
	"--noise4-primary-channel",
	"--noise4-primary-note",
	"--noise4-secondary-channel",
	"--noise4-secondary-note",
	"--noise5-primary-channel",
	"--noise5-primary-note",
	"--noise5-secondary-channel",
	"--noise5-secondary-note",
	"--pitch-background",
	"--pitch-channel-limit",
	"--pitch-primary-channel-hue",
	"--pitch-primary-channel-hue-scale",
	"--pitch-primary-channel-lum",
	"--pitch-primary-channel-lum-scale",
	"--pitch-primary-channel-sat",
	"--pitch-primary-channel-sat-scale",
	"--pitch-primary-note-hue",
	"--pitch-primary-note-hue-scale",
	"--pitch-primary-note-lum",
	"--pitch-primary-note-lum-scale",
	"--pitch-primary-note-sat",
	"--pitch-primary-note-sat-scale",
	"--pitch-secondary-channel-hue",
	"--pitch-secondary-channel-hue-scale",
	"--pitch-secondary-channel-lum",
	"--pitch-secondary-channel-lum-scale",
	"--pitch-secondary-channel-sat",
	"--pitch-secondary-channel-sat-scale",
	"--pitch-secondary-note-hue",
	"--pitch-secondary-note-hue-scale",
	"--pitch-secondary-note-lum",
	"--pitch-secondary-note-lum-scale",
	"--pitch-secondary-note-sat",
	"--pitch-secondary-note-sat-scale",
	"--pitch1-background",
	"--pitch1-primary-channel",
	"--pitch1-primary-note",
	"--pitch1-secondary-channel",
	"--pitch1-secondary-note",
	"--pitch10-primary-channel",
	"--pitch10-primary-note",
	"--pitch10-secondary-channel",
	"--pitch10-secondary-note",
	"--pitch2-primary-channel",
	"--pitch2-primary-note",
	"--pitch2-secondary-channel",
	"--pitch2-secondary-note",
	"--pitch3-primary-channel",
	"--pitch3-primary-note",
	"--pitch3-secondary-channel",
	"--pitch3-secondary-note",
	"--pitch4-primary-channel",
	"--pitch4-primary-note",
	"--pitch4-secondary-channel",
	"--pitch4-secondary-note",
	"--pitch5-primary-channel",
	"--pitch5-primary-note",
	"--pitch5-secondary-channel",
	"--pitch5-secondary-note",
	"--pitch6-primary-channel",
	"--pitch6-primary-note",
	"--pitch6-secondary-channel",
	"--pitch6-secondary-note",
	"--pitch7-primary-channel",
	"--pitch7-primary-note",
	"--pitch7-secondary-channel",
	"--pitch7-secondary-note",
	"--pitch8-primary-channel",
	"--pitch8-primary-note",
	"--pitch8-secondary-channel",
	"--pitch8-secondary-note",
	"--pitch9-primary-channel",
	"--pitch9-primary-note",
	"--pitch9-secondary-channel",
	"--pitch9-secondary-note",
	"--third-note",
	"--tonic",
	"--use-color-formula",
] as const;

export const designTokenCssVars = [
	"--anim-duration-fast",
	"--anim-duration-modal",
	"--anim-duration-normal",
	"--anim-duration-slow",
	"--anim-duration-slower",
	"--anim-duration-slowest",
	"--anim-easing-ease",
	"--anim-easing-ease-in",
	"--anim-easing-ease-out",
	"--anim-easing-linear",
	"--backdrop-blur",
	"--backdrop-blur-heavy",
	"--backdrop-dim",
	"--border-radius-full",
	"--border-radius-large",
	"--border-radius-medium",
	"--border-radius-rem-lg",
	"--border-radius-rem-md",
	"--border-radius-rem-sm",
	"--border-width-default",
	"--border-width-hairline",
	"--border-width-thick",
	"--font-family",
	"--font-family-input",
	"--font-family-mono",
	"--font-size-2xl",
	"--font-size-lg",
	"--font-size-md",
	"--font-size-sm",
	"--font-size-xl",
	"--font-size-xs",
	"--font-weight-bold",
	"--font-weight-medium",
	"--font-weight-normal",
	"--font-weight-semibold",
	"--gap-lg",
	"--gap-md",
	"--gap-rem-lg",
	"--gap-rem-md",
	"--gap-rem-sm",
	"--gap-rem-xl",
	"--gap-sm",
	"--gap-xl",
	"--gap-xs",
	"--icon-lg",
	"--icon-md",
	"--icon-sm",
	"--line-height-normal",
	"--line-height-relaxed",
	"--line-height-tight",
	"--opacity-dim",
	"--opacity-full",
	"--opacity-muted",
	"--opacity-secondary",
	"--opacity-surface",
	"--padding-10",
	"--padding-12",
	"--padding-16",
	"--padding-2",
	"--padding-4",
	"--padding-6",
	"--padding-8",
	"--padding-rem-lg",
	"--padding-rem-md",
	"--padding-rem-sm",
	"--padding-rem-xl",
	"--padding-xs",
	"--radius-left",
	"--radius-right",
	"--shadow-modal",
	"--shadow-none",
	"--shadow-subtle",
	"--sizing-button",
	"--sizing-input-lg",
	"--sizing-input-md",
	"--sizing-input-sm",
	"--sizing-widget-lg",
	"--sizing-widget-md",
	"--sizing-widget-sm",
	"--spacing-lg",
	"--spacing-md",
	"--spacing-sm",
	"--spacing-xl",
	"--spacing-xs",
	"--spacing-xxl",
	"--z-above",
	"--z-base",
	"--z-below",
	"--z-dropdown",
	"--z-modal",
	"--z-overlay",
	"--z-toast",
] as const;

export const iconSymbolCssVars = [
	"--add-symbol",
	"--checkmark-symbol",
	"--close-symbol",
	"--customize-dial-symbol",
	"--drum-symbol",
	"--edit-pencil-symbol",
	"--export-symbol",
	"--file-page-symbol",
	"--instrument-copy-symbol",
	"--instrument-paste-symbol",
	"--internal-add-symbol",
	"--internal-checkmark-symbol",
	"--internal-close-symbol",
	"--internal-customize-dial-symbol",
	"--internal-drum-symbol",
	"--internal-edit-pencil-symbol",
	"--internal-export-symbol",
	"--internal-file-page-symbol",
	"--internal-instrument-copy-symbol",
	"--internal-instrument-paste-symbol",
	"--internal-menu-down-symbol",
	"--internal-minimize-symbol",
	"--internal-mod-key-symbol",
	"--internal-muted-symbol",
	"--internal-next-bar-symbol",
	"--internal-pause-symbol",
	"--internal-piano-key-symbol",
	"--internal-play-symbol",
	"--internal-popout-symbol",
	"--internal-preferences-gear-symbol",
	"--internal-prev-bar-symbol",
	"--internal-record-symbol",
	"--internal-select-arrows-symbol",
	"--internal-stop-symbol",
	"--internal-unmuted-symbol",
	"--internal-volume-symbol",
	"--internal-zoom-in-symbol",
	"--internal-zoom-out-symbol",
	"--menu-down-symbol",
	"--minimize-symbol",
	"--muted-symbol",
	"--next-bar-symbol",
	"--pause-symbol",
	"--piano-key-symbol",
	"--play-symbol",
	"--popout-symbol",
	"--preferences-gear-symbol",
	"--prev-bar-symbol",
	"--record-symbol",
	"--select-arrows-symbol",
	"--stop-symbol",
	"--unmuted-symbol",
	"--volume-symbol",
	"--zoom-in-symbol",
	"--zoom-out-symbol",
] as const;

export const interactionStateCssVars = [
	"--background-color-dim",
	"--background-color-lit",
	"--hover-color-accent",
	"--hover-color-idle",
	"--slider-track",
	"--text-color-lit",
	"--tip-text",
] as const;

export const layoutTokenCssVars = [
	"--button-size",
	"--flex-fill",
	"--flex-fit",
	"--flex-stretch",
	"--input-width-sm",
	"--pane-gap",
	"--settings-area-width",
] as const;

export const promptSurfaceCssVars = [
	"--base02-surface",
	"--base03-muted",
	"--cta-bg",
	"--cta-fg",
	"--empty-sample-bar",
	"--prompt-backdrop-filter",
	"--prompt-bg-color",
	"--prompt-list-item-bg",
	"--prompt-list-item-bg-hover",
	"--prompt-list-item-border",
	"--prompt-row-height",
	"--prompt-titlebar-text",
	"--prompt-width-lg",
	"--prompt-width-md",
	"--prompt-width-sm",
	"--subtext",
	"--tab-inactive-bg",
	"--tab-inactive-fg",
] as const;

export const miscCssVars = [
	"--ease",
	"--input-box-outline",
	"--mute-editor-text-dim",
] as const;

export const cssVariableContract = {
	themeCore: themeCoreCssVars,
	channelColor: channelColorCssVars,
	designToken: designTokenCssVars,
	iconSymbol: iconSymbolCssVars,
	interactionState: interactionStateCssVars,
	layoutToken: layoutTokenCssVars,
	promptSurface: promptSurfaceCssVars,
	misc: miscCssVars,
} as const;

export const knownCssVars = [
	...themeCoreCssVars,
	...channelColorCssVars,
	...designTokenCssVars,
	...iconSymbolCssVars,
	...interactionStateCssVars,
	...layoutTokenCssVars,
	...promptSurfaceCssVars,
	...miscCssVars,
] as const;

export const knownCssVariables = knownCssVars;

export type CssVarName = (typeof knownCssVars)[number];

export const knownCssVarSet: ReadonlySet<string> = new Set<string>(knownCssVars);

export function isKnownCssVariable(name: string): name is CssVarName {
	return knownCssVarSet.has(name);
}

export const requiredThemeCssVars = [
	"--editor-background",
	"--primary-text",
	"--secondary-text",
	"--ui-widget-background",
	"--indicator-primary",
	"--indicator-secondary",
] as const satisfies readonly CssVarName[];
