// inventory.ts
//
// Purpose: Declarative registry of all editor input bindings
//
// This module:
// - Enumerates every keyboard shortcut with source file and handler ref
// - Enumerates every mouse/touch interaction with source file and concern
// - Acts as the single audit surface for input drift detection

export type InputKind = "key" | "mouse" | "touch" | "wheel" | "scroll";

export type InputConcern =
	| "playback"
	| "navigation"
	| "editing"
	| "selection"
	| "channels"
	| "presets"
	| "views"
	| "file"
	| "live-input"
	| "pattern-draw"
	| "pattern-select"
	| "loop-region"
	| "track-scroll"
	| "mod-recording";

export interface InputBinding {
	id: string;
	kind: InputKind;
	concern: InputConcern;
	sourceFile: string;
	handler: string;
	keys?: string;
	modifiers?: string[];
	condition?: string;
	detail?: string;
	/** Optional category for display in the keyboard shortcuts prompt. */
	displayCategory?: string;
}

export const inputBindings: InputBinding[] = [
	{
		id: "playback_toggle",
		kind: "key",
		concern: "playback",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Space",
		detail: "Toggle play/pause",
	},
	{
		id: "playback_toggle_from_cursor",
		kind: "key",
		concern: "playback",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Space",
		modifiers: ["shift"],
		detail: "Play from cursor and set loop to selection",
	},
	{
		id: "playback_record",
		kind: "key",
		concern: "playback",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Space",
		modifiers: ["ctrl"],
		detail: "Toggle recording",
	},
	{
		id: "playback_record_clear_loop",
		kind: "key",
		concern: "playback",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "P",
		modifiers: ["ctrl"],
		detail: "Toggle recording and clear loop",
	},
	{
		id: "playback_go_to_start",
		kind: "key",
		concern: "playback",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "F",
		modifiers: ["ctrl"],
		condition: "when not canPlayNotes",
		detail: "Go to start of song",
	},
	{
		id: "playback_go_to_loop_start",
		kind: "key",
		concern: "playback",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "F",
		modifiers: ["shift"],
		condition: "when not canPlayNotes",
		detail: "Go to loop start",
	},
	{
		id: "playback_play_current_bar",
		kind: "key",
		concern: "playback",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "H",
		modifiers: ["ctrl"],
		condition: "when not canPlayNotes",
		detail: "Play from current bar",
	},
	{
		id: "playback_prev_bar",
		kind: "key",
		concern: "playback",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "[",
		modifiers: ["ctrl"],
		condition: "when not canPlayNotes",
		detail: "Go to previous bar",
	},
	{
		id: "playback_next_bar",
		kind: "key",
		concern: "playback",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "]",
		modifiers: ["ctrl"],
		condition: "when not canPlayNotes",
		detail: "Go to next bar",
	},
	{
		id: "playback_mute_channel",
		kind: "key",
		concern: "playback",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "S",
		modifiers: ["shift"],
		condition: "when channel muting enabled",
		detail: "Mute channel",
	},
	{
		id: "playback_solo_channel",
		kind: "key",
		concern: "playback",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "S",
		condition: "when channel muting enabled",
		detail: "Solo channel",
	},
	{
		id: "playback_mute_channels",
		kind: "key",
		concern: "playback",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "M",
		modifiers: ["ctrl"],
		condition: "when channel muting enabled",
		detail: "Mute all channels (Shift to unmute)",
	},
	{
		id: "playback_open_song_player",
		kind: "key",
		concern: "playback",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "P",
		modifiers: ["shift", "ctrl"],
		detail: "Open song in player view",
	},

	{
		id: "nav_mode_enter",
		kind: "key",
		concern: "navigation",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: ";",
		modifiers: ["ctrl"],
		detail: "Enter keyboard navigation mode",
	},
	{
		id: "nav_mode_bar_left",
		kind: "key",
		concern: "navigation",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "H",
		condition: "while keyboard navigation mode is active",
		detail: "Previous bar (Shift extends selection)",
	},
	{
		id: "nav_mode_bar_right",
		kind: "key",
		concern: "navigation",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "L",
		condition: "while keyboard navigation mode is active",
		detail: "Next bar (Shift extends selection)",
	},
	{
		id: "nav_mode_channel_up",
		kind: "key",
		concern: "navigation",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "K",
		condition: "while keyboard navigation mode is active",
		detail: "Previous channel (Shift extends selection)",
	},
	{
		id: "nav_mode_channel_down",
		kind: "key",
		concern: "navigation",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "J",
		condition: "while keyboard navigation mode is active",
		detail: "Next channel (Shift extends selection)",
	},
	{
		id: "nav_mode_exit",
		kind: "key",
		concern: "navigation",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Escape",
		condition: "while keyboard navigation mode is active",
		detail: "Exit keyboard navigation mode",
	},
	{
		id: "nav_channel_up",
		kind: "key",
		concern: "navigation",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Up",
		detail: "Navigate to previous channel",
	},
	{
		id: "nav_channel_down",
		kind: "key",
		concern: "navigation",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Down",
		detail: "Navigate to next channel",
	},
	{
		id: "nav_bar_left",
		kind: "key",
		concern: "navigation",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Left",
		detail: "Navigate to previous bar",
	},
	{
		id: "nav_bar_right",
		kind: "key",
		concern: "navigation",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Right",
		detail: "Navigate to next bar",
	},
	{
		id: "nav_swap_channel_up",
		kind: "key",
		concern: "navigation",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Up",
		modifiers: ["ctrl"],
		detail: "Swap channel up",
	},
	{
		id: "nav_swap_channel_down",
		kind: "key",
		concern: "navigation",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Down",
		modifiers: ["ctrl"],
		detail: "Swap channel down",
	},
	{
		id: "nav_bar_scroll_click",
		kind: "mouse",
		concern: "track-scroll",
		sourceFile: "editor/components/bar-scroll-bar.ts",
		handler: "_whenMousePressed",
		detail: "Click to scroll bar view left/right or drag handle",
	},
	{
		id: "nav_bar_scroll_drag",
		kind: "mouse",
		concern: "track-scroll",
		sourceFile: "editor/components/bar-scroll-bar.ts",
		handler: "_whenMouseMoved",
		detail: "Drag scroll handle to navigate bars",
	},
	{
		id: "nav_bar_scroll_touch",
		kind: "touch",
		concern: "track-scroll",
		sourceFile: "editor/components/bar-scroll-bar.ts",
		handler: "_whenTouchPressed",
		detail: "Touch drag to scroll bars",
	},
	{
		id: "nav_octave_scroll_click",
		kind: "mouse",
		concern: "track-scroll",
		sourceFile: "editor/components/octave-scroll-bar.ts",
		handler: "_whenMousePressed",
		condition: "only for non-noise/non-mod channels",
		detail: "Click to scroll octave view or drag handle",
	},
	{
		id: "nav_octave_scroll_drag",
		kind: "mouse",
		concern: "track-scroll",
		sourceFile: "editor/components/octave-scroll-bar.ts",
		handler: "_whenMouseMoved",
		detail: "Drag octave handle to change visible range",
	},
	{
		id: "nav_octave_scroll_touch",
		kind: "touch",
		concern: "track-scroll",
		sourceFile: "editor/components/octave-scroll-bar.ts",
		handler: "_whenTouchPressed",
		detail: "Touch drag to scroll octaves",
	},

	{
		id: "edit_undo",
		kind: "key",
		concern: "editing",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Z",
		condition: "when not canPlayNotes",
		detail: "Undo",
	},
	{
		id: "edit_redo",
		kind: "key",
		concern: "editing",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Z",
		modifiers: ["shift"],
		condition: "when not canPlayNotes",
		detail: "Redo",
	},
	{
		id: "edit_redo_y",
		kind: "key",
		concern: "editing",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Y",
		condition: "when not canPlayNotes",
		detail: "Redo (alternate)",
	},
	{
		id: "edit_cut",
		kind: "key",
		concern: "editing",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "X",
		condition: "when not canPlayNotes",
		detail: "Cut notes",
	},
	{
		id: "edit_copy",
		kind: "key",
		concern: "editing",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "C",
		condition: "when not canPlayNotes",
		detail: "Copy notes",
	},
	{
		id: "edit_paste",
		kind: "key",
		concern: "editing",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "V",
		condition: "when not canPlayNotes",
		detail: "Paste notes",
	},
	{
		id: "edit_paste_instrument",
		kind: "key",
		concern: "editing",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "V",
		modifiers: ["shift"],
		condition: "when not canPlayNotes",
		detail: "Paste instrument",
	},
	{
		id: "edit_paste_numbers",
		kind: "key",
		concern: "editing",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "V",
		modifiers: ["ctrl", "shift"],
		condition: "when not canPlayNotes",
		detail: "Paste pattern numbers",
	},
	{
		id: "edit_duplicate",
		kind: "key",
		concern: "editing",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "D",
		modifiers: ["ctrl"],
		condition: "when not canPlayNotes",
		detail: "Duplicate patterns",
	},
	{
		id: "edit_delete",
		kind: "key",
		concern: "editing",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Delete",
		detail: "Reset pattern to 0",
	},
	{
		id: "edit_insert_bars",
		kind: "key",
		concern: "editing",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Enter",
		detail: "Insert bars",
	},
	{
		id: "edit_insert_bars_before",
		kind: "key",
		concern: "editing",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Enter",
		modifiers: ["shift"],
		detail: "Insert bars before selection",
	},
	{
		id: "edit_delete_bars",
		kind: "key",
		concern: "editing",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Backspace",
		detail: "Delete bars",
	},
	{
		id: "edit_insert_channel",
		kind: "key",
		concern: "editing",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Enter",
		modifiers: ["ctrl"],
		detail: "Insert channel",
	},
	{
		id: "edit_delete_channel",
		kind: "key",
		concern: "editing",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Backspace",
		modifiers: ["ctrl"],
		detail: "Delete channel",
	},
	{
		id: "edit_add_instrument",
		kind: "key",
		concern: "editing",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Enter",
		modifiers: ["alt"],
		detail: "Add instrument to channel",
	},
	{
		id: "edit_remove_instrument",
		kind: "key",
		concern: "editing",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Backspace",
		modifiers: ["alt"],
		detail: "Remove instrument from channel",
	},
	{
		id: "edit_copy_instrument",
		kind: "key",
		concern: "editing",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "C",
		modifiers: ["shift"],
		detail: "Copy instrument",
	},
	{
		id: "edit_pattern_digit_entry",
		kind: "key",
		concern: "editing",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "0-9",
		condition: "when not canPlayNotes",
		detail: "Enter pattern number digits",
	},
	{
		id: "edit_pattern_draw_mouse",
		kind: "mouse",
		concern: "pattern-draw",
		sourceFile: "editor/components/pattern-editor.ts",
		handler: "_whenMousePressed",
		detail: "Start note editing/selection in pattern editor",
	},
	{
		id: "edit_pattern_draw_drag",
		kind: "mouse",
		concern: "pattern-draw",
		sourceFile: "editor/components/pattern-editor.ts",
		handler: "_whenMouseMoved",
		detail: "Drag notes, resize (pin or full-height edge grab), move selection",
	},
	{
		id: "edit_pattern_draw_release",
		kind: "mouse",
		concern: "pattern-draw",
		sourceFile: "editor/components/pattern-editor.ts",
		handler: "_whenCursorReleased",
		detail: "End editing, record change",
	},
	{
		id: "edit_pattern_draw_touch",
		kind: "touch",
		concern: "pattern-draw",
		sourceFile: "editor/components/pattern-editor.ts",
		handler: "_whenTouchPressed",
		detail: "Start touch note editing",
	},
	{
		id: "edit_pattern_draw_wheel",
		kind: "wheel",
		concern: "pattern-draw",
		sourceFile: "editor/components/pattern-editor.ts",
		handler: "_whenWheel",
		condition: "when not mouseDown",
		detail: "Scroll to adjust hovered note length (nearest end) or default placement length on empty space",
	},
	{
		id: "edit_track_select_mouse",
		kind: "mouse",
		concern: "pattern-select",
		sourceFile: "editor/components/track-editor.ts",
		handler: "_whenMousePressed",
		detail: "Start bar/channel pattern selection",
	},
	{
		id: "edit_track_select_drag",
		kind: "mouse",
		concern: "pattern-select",
		sourceFile: "editor/components/track-editor.ts",
		handler: "_whenMouseMoved",
		detail: "Drag box selection",
	},
	{
		id: "edit_track_select_release",
		kind: "mouse",
		concern: "pattern-select",
		sourceFile: "editor/components/track-editor.ts",
		handler: "_whenMouseReleased",
		detail: "End selection, change pattern on click",
	},
	{
		id: "edit_track_select_touch",
		kind: "touch",
		concern: "pattern-select",
		sourceFile: "editor/components/track-editor.ts",
		handler: "_whenSelectPressed",
		detail: "Start touch selection",
	},
	{
		id: "edit_filter_draw_mouse",
		kind: "mouse",
		concern: "editing",
		sourceFile: "editor/components/filter-editor.ts",
		handler: "_whenMousePressed",
		condition: "when _larger is true",
		detail: "Start filter control point editing",
	},
	{
		id: "edit_filter_draw_drag",
		kind: "mouse",
		concern: "editing",
		sourceFile: "editor/components/filter-editor.ts",
		handler: "_whenMouseMoved",
		detail: "Drag filter points, add/delete points",
	},
	{
		id: "edit_filter_draw_touch",
		kind: "touch",
		concern: "editing",
		sourceFile: "editor/components/filter-editor.ts",
		handler: "_whenTouchPressed",
		detail: "Start touch filter editing",
	},
	{
		id: "edit_filter_undo",
		kind: "key",
		concern: "editing",
		sourceFile: "editor/components/filter-editor.ts",
		handler: "_whenKeyPressed",
		keys: "Z",
		condition: "only in larger filter editor",
		detail: "Undo in filter editor",
	},
	{
		id: "edit_filter_redo",
		kind: "key",
		concern: "editing",
		sourceFile: "editor/components/filter-editor.ts",
		handler: "_whenKeyPressed",
		keys: "Y",
		condition: "only in larger filter editor",
		detail: "Redo in filter editor",
	},
	{
		id: "edit_fade_draw_mouse",
		kind: "mouse",
		concern: "editing",
		sourceFile: "editor/components/fade-in-out-editor.ts",
		handler: "_whenMousePressed",
		detail: "Start fade in/out editing",
	},
	{
		id: "edit_fade_draw_drag",
		kind: "mouse",
		concern: "editing",
		sourceFile: "editor/components/fade-in-out-editor.ts",
		handler: "_whenMouseMoved",
		detail: "Drag fade in/out points",
	},
	{
		id: "edit_fade_draw_touch",
		kind: "touch",
		concern: "editing",
		sourceFile: "editor/components/fade-in-out-editor.ts",
		handler: "_whenTouchPressed",
		detail: "Start touch fade editing",
	},
	{
		id: "edit_envelope_change",
		kind: "mouse",
		concern: "editing",
		sourceFile: "editor/components/envelope-editor.ts",
		handler: "_onChange",
		detail: "Change envelope target, type, waveform, or settings",
	},
	{
		id: "edit_envelope_delete",
		kind: "mouse",
		concern: "editing",
		sourceFile: "editor/components/envelope-editor.ts",
		handler: "_onClick",
		detail: "Remove envelope",
	},
	{
		id: "edit_envelope_copy",
		kind: "mouse",
		concern: "editing",
		sourceFile: "editor/components/envelope-editor.ts",
		handler: "_onClick",
		detail: "Copy envelope to localStorage",
	},
	{
		id: "edit_envelope_paste",
		kind: "mouse",
		concern: "editing",
		sourceFile: "editor/components/envelope-editor.ts",
		handler: "_onClick",
		detail: "Paste envelope from localStorage",
	},
	{
		id: "edit_spectrum_draw_mouse",
		kind: "mouse",
		concern: "editing",
		sourceFile: "editor/components/spectrum-editor.ts",
		handler: "_whenMousePressed",
		detail: "Start spectrum editing",
	},
	{
		id: "edit_spectrum_draw_drag",
		kind: "mouse",
		concern: "editing",
		sourceFile: "editor/components/spectrum-editor.ts",
		handler: "_whenMouseMoved",
		detail: "Drag spectrum points",
	},
	{
		id: "edit_spectrum_draw_touch",
		kind: "touch",
		concern: "editing",
		sourceFile: "editor/components/spectrum-editor.ts",
		handler: "_whenTouchPressed",
		detail: "Start touch spectrum editing",
	},
	{
		id: "edit_harmonics_draw_mouse",
		kind: "mouse",
		concern: "editing",
		sourceFile: "editor/components/harmonics-editor.ts",
		handler: "_whenMousePressed",
		detail: "Start harmonics editing",
	},
	{
		id: "edit_harmonics_draw_drag",
		kind: "mouse",
		concern: "editing",
		sourceFile: "editor/components/harmonics-editor.ts",
		handler: "_whenMouseMoved",
		detail: "Drag harmonics points",
	},
	{
		id: "edit_harmonics_draw_touch",
		kind: "touch",
		concern: "editing",
		sourceFile: "editor/components/harmonics-editor.ts",
		handler: "_whenTouchPressed",
		detail: "Start touch harmonics editing",
	},
	{
		id: "edit_loop_drag_mouse",
		kind: "mouse",
		concern: "loop-region",
		sourceFile: "editor/components/loop-editor.ts",
		handler: "_whenMousePressed",
		detail: "Start loop region drag",
	},
	{
		id: "edit_loop_drag_move",
		kind: "mouse",
		concern: "loop-region",
		sourceFile: "editor/components/loop-editor.ts",
		handler: "_whenMouseMoved",
		detail: "Drag loop points",
	},
	{
		id: "edit_loop_drag_touch",
		kind: "touch",
		concern: "loop-region",
		sourceFile: "editor/components/loop-editor.ts",
		handler: "_whenTouchPressed",
		detail: "Start touch loop drag",
	},
	{
		id: "edit_piano_play_mouse",
		kind: "mouse",
		concern: "live-input",
		sourceFile: "editor/components/piano.ts",
		handler: "_whenMousePressed",
		detail: "Start live note input on piano",
	},
	{
		id: "edit_piano_play_drag",
		kind: "mouse",
		concern: "live-input",
		sourceFile: "editor/components/piano.ts",
		handler: "_whenMouseMoved",
		detail: "Move cursor, play notes while dragging",
	},
	{
		id: "edit_piano_play_touch",
		kind: "touch",
		concern: "live-input",
		sourceFile: "editor/components/piano.ts",
		handler: "_whenTouchPressed",
		detail: "Start touch live input",
	},
	{
		id: "edit_slider_input",
		kind: "mouse",
		concern: "editing",
		sourceFile: "editor/ui/sliders/slider.ts",
		handler: "_whenInput",
		detail: "Set prospective change on slider input",
	},
	{
		id: "edit_slider_commit",
		kind: "mouse",
		concern: "editing",
		sourceFile: "editor/ui/sliders/slider.ts",
		handler: "_whenChange",
		detail: "Commit slider change to undo history",
	},
	{
		id: "edit_slider_reset",
		kind: "mouse",
		concern: "editing",
		sourceFile: "editor/ui/sliders/slider.ts",
		handler: "_onDoubleClick",
		condition: "only if doubleClickSliderReset pref enabled",
		detail: "Reset slider to default on double-click",
	},
	{
		id: "edit_input_box_input",
		kind: "mouse",
		concern: "editing",
		sourceFile: "editor/ui/inputs/input-box.ts",
		handler: "_whenInput",
		detail: "Set prospective change on input box",
	},
	{
		id: "edit_input_box_commit",
		kind: "mouse",
		concern: "editing",
		sourceFile: "editor/ui/inputs/input-box.ts",
		handler: "_whenChange",
		detail: "Commit input box change to undo history",
	},
	{
		id: "edit_wheel_step",
		kind: "wheel",
		concern: "editing",
		sourceFile: "editor/ui/base/input.ts",
		handler: "addWheelSupport",
		condition: "only if enableScrollStep localStorage is true",
		detail: "Increment/decrement number input by step on scroll",
	},
	{
		id: "edit_toggle_click",
		kind: "mouse",
		concern: "editing",
		sourceFile: "editor/ui/buttons/toggle-button.ts",
		handler: "onToggle",
		detail: "Select toggle button option",
	},
	{
		id: "edit_algorithm_node_mouse",
		kind: "mouse",
		concern: "editing",
		sourceFile: "editor/rendering/custom-algorithm-canvas.ts",
		handler: "_onMouseDown",
		detail: "Start algorithm node selection",
	},
	{
		id: "edit_algorithm_node_drag",
		kind: "mouse",
		concern: "editing",
		sourceFile: "editor/rendering/custom-algorithm-canvas.ts",
		handler: "_onMouseMove",
		detail: "Drag algorithm nodes, toggle modulation",
	},
	{
		id: "edit_chip_wave_draw_mouse",
		kind: "mouse",
		concern: "editing",
		sourceFile: "editor/rendering/custom-chip-canvas.ts",
		handler: "_onMouseDown",
		detail: "Start custom chip waveform drawing",
	},
	{
		id: "edit_chip_wave_draw_drag",
		kind: "mouse",
		concern: "editing",
		sourceFile: "editor/rendering/custom-chip-canvas.ts",
		handler: "_onMouseMove",
		detail: "Draw custom chip waveform",
	},
	{
		id: "edit_mute_click",
		kind: "mouse",
		concern: "channels",
		sourceFile: "editor/components/mute-editor.ts",
		handler: "_onClick",
		detail: "Toggle channel mute",
	},
	{
		id: "edit_mute_dropdown",
		kind: "mouse",
		concern: "channels",
		sourceFile: "editor/components/mute-editor.ts",
		handler: "_channelDropDownHandler",
		detail: "Rename, move, mute, solo, insert, delete channel",
	},
	{
		id: "edit_mute_keyup",
		kind: "key",
		concern: "channels",
		sourceFile: "editor/components/mute-editor.ts",
		handler: "onKeyUp",
		keys: "Escape",
		detail: "Close channel dropdown",
	},
	{
		id: "edit_mute_keyup_enter",
		kind: "key",
		concern: "channels",
		sourceFile: "editor/components/mute-editor.ts",
		handler: "onKeyUp",
		keys: "Enter",
		detail: "Close channel dropdown",
	},

	{
		id: "select_all",
		kind: "key",
		concern: "selection",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "A",
		condition: "when not canPlayNotes",
		detail: "Select all notes",
	},
	{
		id: "select_channel",
		kind: "key",
		concern: "selection",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "A",
		modifiers: ["shift"],
		condition: "when not canPlayNotes",
		detail: "Select current channel",
	},
	{
		id: "select_clear",
		kind: "key",
		concern: "selection",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Escape",
		condition: "when not Ctrl/Meta held",
		detail: "Clear selection",
	},
	{
		id: "select_box_up",
		kind: "key",
		concern: "selection",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Up",
		modifiers: ["shift"],
		detail: "Extend box selection up",
	},
	{
		id: "select_box_down",
		kind: "key",
		concern: "selection",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Down",
		modifiers: ["shift"],
		detail: "Extend box selection down",
	},
	{
		id: "select_box_left",
		kind: "key",
		concern: "selection",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Left",
		modifiers: ["shift"],
		detail: "Extend box selection left",
	},
	{
		id: "select_box_right",
		kind: "key",
		concern: "selection",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Right",
		modifiers: ["shift"],
		detail: "Extend box selection right",
	},

	{
		id: "channel_settings",
		kind: "key",
		concern: "channels",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Q",
		modifiers: ["ctrl"],
		condition: "when not canPlayNotes",
		detail: "Open channel settings",
	},
	{
		id: "channel_add_external",
		kind: "key",
		concern: "channels",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Q",
		modifiers: ["shift", "ctrl"],
		condition: "when not canPlayNotes",
		detail: "Add external channel",
	},
	{
		id: "channel_volume_visualizer",
		kind: "key",
		concern: "channels",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "G",
		condition: "when not canPlayNotes",
		detail: "Open channel volume visualizer",
	},

	{
		id: "preset_next",
		kind: "key",
		concern: "presets",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "T",
		condition: "when not canPlayNotes",
		detail: "Next preset",
	},
	{
		id: "preset_selector",
		kind: "key",
		concern: "presets",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "T",
		modifiers: ["shift"],
		condition: "when not canPlayNotes",
		detail: "Open preset selector",
	},
	{
		id: "preset_random",
		kind: "key",
		concern: "presets",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "R",
		modifiers: ["ctrl"],
		condition: "when not canPlayNotes",
		detail: "Random preset",
	},
	{
		id: "preset_random_generated",
		kind: "key",
		concern: "presets",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "R",
		modifiers: ["ctrl", "shift"],
		condition: "when not canPlayNotes",
		detail: "Random generated instrument",
	},
	{
		id: "preset_random_generated_alt",
		kind: "key",
		concern: "presets",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "R",
		modifiers: ["ctrl", "alt"],
		condition: "when not canPlayNotes",
		detail: "Random generated instrument (alt)",
	},
	{
		id: "preset_copy_json",
		kind: "key",
		concern: "presets",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "I",
		modifiers: ["shift", "ctrl"],
		condition: "when not canPlayNotes",
		detail: "Copy instrument JSON to clipboard",
	},

	{
		id: "view_shortcuts",
		kind: "key",
		concern: "views",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "/",
		modifiers: ["shift"],
		condition: "when not canPlayNotes",
		detail: "Open keyboard shortcuts help",
	},
	{
		id: "view_shortcuts_search",
		kind: "mouse",
		concern: "views",
		sourceFile: "editor/prompts/keyboard-shortcuts-prompt.ts",
		handler: "_onSearch",
		detail: "Filter shortcuts by search text",
	},
	{
		id: "view_shortcuts_close",
		kind: "key",
		concern: "views",
		sourceFile: "editor/prompts/keyboard-shortcuts-prompt.ts",
		handler: "whenKeyPressed",
		keys: "Escape",
		condition: "when prompt is open",
		detail: "Close shortcuts prompt",
	},
	{
		id: "view_beats_per_bar",
		kind: "key",
		concern: "views",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "B",
		modifiers: ["shift", "ctrl"],
		condition: "when not canPlayNotes",
		detail: "Open beats per bar prompt",
	},
	{
		id: "view_bar_count",
		kind: "key",
		concern: "views",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "L",
		condition: "when not canPlayNotes",
		detail: "Open bar count prompt",
	},
	{
		id: "view_limiter_settings",
		kind: "key",
		concern: "views",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "L",
		modifiers: ["shift"],
		condition: "when not canPlayNotes",
		detail: "Open limiter settings",
	},
	{
		id: "view_eq_song",
		kind: "key",
		concern: "views",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "E",
		modifiers: ["ctrl"],
		condition: "when not canPlayNotes",
		detail: "Open song EQ filter settings",
	},
	{
		id: "view_eq_instrument",
		kind: "key",
		concern: "views",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "E",
		modifiers: ["shift"],
		condition: "when not canPlayNotes",
		detail: "Open instrument EQ filter settings",
	},
	{
		id: "view_note_filter",
		kind: "key",
		concern: "views",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "N",
		modifiers: ["shift"],
		condition: "when not canPlayNotes",
		detail: "Open custom note filter settings",
	},
	{
		id: "view_envelope_toggle_dropdowns",
		kind: "key",
		concern: "views",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "E",
		modifiers: ["alt"],
		detail: "Toggle all envelope dropdowns open/closed",
	},
	{
		id: "view_fm_toggle_dropdowns",
		kind: "key",
		concern: "views",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "F",
		modifiers: ["alt"],
		detail: "Toggle all FM operator dropdowns open/closed",
	},
	{
		id: "view_move_notes_sideways",
		kind: "key",
		concern: "views",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "W",
		condition: "when not canPlayNotes",
		detail: "Open move notes sideways prompt",
	},
	{
		id: "view_euclidean_rhythm",
		kind: "key",
		concern: "views",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "E",
		modifiers: ["ctrl"],
		condition: "when not canPlayNotes",
		detail: "Open euclidean rhythm generator",
	},
	{
		id: "view_song_recovery",
		kind: "key",
		concern: "views",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "`",
		condition: "when not canPlayNotes",
		detail: "Open song recovery prompt",
	},
	{
		id: "view_new_song",
		kind: "key",
		concern: "views",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "`",
		modifiers: ["shift"],
		detail: "Create new blank song",
	},
	{
		id: "view_shorten_url",
		kind: "key",
		concern: "views",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "U",
		modifiers: ["shift"],
		detail: "Open shortened URL for song",
	},
	{
		id: "view_zoom_in",
		kind: "mouse",
		concern: "views",
		sourceFile: "editor/components/pattern-area.ts",
		handler: "onZoomIn",
		detail: "Zoom in pattern view",
	},
	{
		id: "view_zoom_out",
		kind: "mouse",
		concern: "views",
		sourceFile: "editor/components/pattern-area.ts",
		handler: "onZoomOut",
		detail: "Zoom out pattern view",
	},
	{
		id: "view_spectrum_prompt_key",
		kind: "key",
		concern: "views",
		sourceFile: "editor/components/spectrum-editor.ts",
		handler: "whenKeyPressed",
		keys: "Enter",
		condition: "when spectrum prompt is open",
		detail: "Save spectrum changes",
	},
	{
		id: "view_spectrum_prompt_play",
		kind: "key",
		concern: "views",
		sourceFile: "editor/components/spectrum-editor.ts",
		handler: "whenKeyPressed",
		keys: "Space",
		condition: "when spectrum prompt is open",
		detail: "Toggle playback in spectrum editor",
	},
	{
		id: "view_spectrum_prompt_undo",
		kind: "key",
		concern: "views",
		sourceFile: "editor/components/spectrum-editor.ts",
		handler: "whenKeyPressed",
		keys: "Z",
		condition: "when spectrum prompt is open",
		detail: "Undo in spectrum editor",
	},
	{
		id: "view_spectrum_prompt_redo",
		kind: "key",
		concern: "views",
		sourceFile: "editor/components/spectrum-editor.ts",
		handler: "whenKeyPressed",
		keys: "Y",
		condition: "when spectrum prompt is open",
		detail: "Redo in spectrum editor",
	},
	{
		id: "view_harmonics_prompt_key",
		kind: "key",
		concern: "views",
		sourceFile: "editor/components/harmonics-editor.ts",
		handler: "whenKeyPressed",
		keys: "Enter",
		condition: "when harmonics prompt is open",
		detail: "Save harmonics changes",
	},
	{
		id: "view_harmonics_prompt_play",
		kind: "key",
		concern: "views",
		sourceFile: "editor/components/harmonics-editor.ts",
		handler: "whenKeyPressed",
		keys: "Space",
		condition: "when harmonics prompt is open",
		detail: "Toggle playback in harmonics editor",
	},
	{
		id: "view_harmonics_prompt_undo",
		kind: "key",
		concern: "views",
		sourceFile: "editor/components/harmonics-editor.ts",
		handler: "whenKeyPressed",
		keys: "Z",
		condition: "when harmonics prompt is open",
		detail: "Undo in harmonics editor",
	},
	{
		id: "view_harmonics_prompt_redo",
		kind: "key",
		concern: "views",
		sourceFile: "editor/components/harmonics-editor.ts",
		handler: "whenKeyPressed",
		keys: "Y",
		condition: "when harmonics prompt is open",
		detail: "Redo in harmonics editor",
	},
	{
		id: "view_loop_prompt_save",
		kind: "key",
		concern: "views",
		sourceFile: "editor/prompts/visual-loop-controls-prompt.ts",
		handler: "whenKeyPressed",
		keys: "Enter",
		condition: "when not on a button",
		detail: "Save loop changes",
	},
	{
		id: "view_loop_prompt_play",
		kind: "key",
		concern: "views",
		sourceFile: "editor/prompts/visual-loop-controls-prompt.ts",
		handler: "whenKeyPressed",
		keys: "Space",
		condition: "when loop prompt is open",
		detail: "Toggle playback",
	},
	{
		id: "view_loop_overlay_zoom_mouse",
		kind: "mouse",
		concern: "views",
		sourceFile: "editor/prompts/visual-loop-controls-prompt.ts",
		handler: "_whenOverlayMouseIsDown",
		detail: "Start waveform zoom selection",
	},
	{
		id: "view_loop_overlay_zoom_drag",
		kind: "mouse",
		concern: "views",
		sourceFile: "editor/prompts/visual-loop-controls-prompt.ts",
		handler: "_whenOverlayMouseMoves",
		detail: "Drag waveform zoom selection",
	},
	{
		id: "view_loop_overlay_zoom_touch",
		kind: "touch",
		concern: "views",
		sourceFile: "editor/prompts/visual-loop-controls-prompt.ts",
		handler: "_whenOverlayTouchIsDown",
		detail: "Start touch waveform zoom",
	},
	{
		id: "view_loop_handle_drag_mouse",
		kind: "mouse",
		concern: "loop-region",
		sourceFile: "editor/prompts/visual-loop-controls-handle.ts",
		handler: "_whenMouseIsDown",
		detail: "Start loop handle drag",
	},
	{
		id: "view_loop_handle_drag_move",
		kind: "mouse",
		concern: "loop-region",
		sourceFile: "editor/prompts/visual-loop-controls-handle.ts",
		handler: "_whenMouseMoves",
		detail: "Drag loop handle",
	},
	{
		id: "view_loop_handle_drag_touch",
		kind: "touch",
		concern: "loop-region",
		sourceFile: "editor/prompts/visual-loop-controls-handle.ts",
		handler: "_whenTouchIsDown",
		detail: "Start touch loop handle drag",
	},

	{
		id: "file_export",
		kind: "key",
		concern: "file",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "S",
		modifiers: ["ctrl"],
		condition: "when not canPlayNotes",
		detail: "Open export prompt",
	},
	{
		id: "file_import",
		kind: "key",
		concern: "file",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "O",
		modifiers: ["ctrl"],
		condition: "when not canPlayNotes",
		detail: "Open import prompt",
	},
	{
		id: "file_export_instrument",
		kind: "key",
		concern: "file",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "S",
		modifiers: ["alt"],
		condition: "when not canPlayNotes",
		detail: "Open export instrument prompt",
	},
	{
		id: "file_import_instrument",
		kind: "key",
		concern: "file",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "O",
		modifiers: ["alt"],
		condition: "when not canPlayNotes",
		detail: "Open import instrument prompt",
	},

	{
		id: "live_play_notes",
		kind: "key",
		concern: "live-input",
		sourceFile: "editor/config/keyboard-layout.ts",
		handler: "handleKeyEvent",
		keys: "A-Z/0-9",
		condition: "when canPlayNotes (no Ctrl/Meta, correct CapsLock)",
		detail: "Play live note preview from keyboard",
	},
	{
		id: "live_release_notes",
		kind: "key",
		concern: "live-input",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyUp",
		keys: "Any",
		detail: "Release live pitches on key up",
	},
	{
		id: "live_midi_input",
		kind: "mouse",
		concern: "live-input",
		sourceFile: "editor/io/midi-input.ts",
		handler: "_onMidiMessage",
		condition: "when MIDI enabled and this tab is MIDI handler",
		detail: "Translate MIDI note-on/off to performed pitches",
	},
	{
		id: "live_transpose_down",
		kind: "key",
		concern: "live-input",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "-",
		modifiers: ["ctrl"],
		condition: "when not canPlayNotes",
		detail: "Transpose selection down",
	},
	{
		id: "live_transpose_up",
		kind: "key",
		concern: "live-input",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "=",
		modifiers: ["ctrl"],
		condition: "when not canPlayNotes",
		detail: "Transpose selection up",
	},
	{
		id: "live_transpose_octave_down",
		kind: "key",
		concern: "live-input",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "-",
		modifiers: ["ctrl", "shift"],
		condition: "when not canPlayNotes",
		detail: "Transpose selection down one octave",
	},
	{
		id: "live_transpose_octave_up",
		kind: "key",
		concern: "live-input",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "=",
		modifiers: ["ctrl", "shift"],
		condition: "when not canPlayNotes",
		detail: "Transpose selection up one octave",
	},

	{
		id: "loop_set_to_selection",
		kind: "key",
		concern: "loop-region",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "B",
		modifiers: ["ctrl"],
		condition: "when not canPlayNotes",
		detail: "Set loop to selection (or clear if already set)",
	},

	{
		id: "mod_recording_toggle",
		kind: "key",
		concern: "mod-recording",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Space",
		condition: "when recording mode active",
		detail: "Toggle recording (stop recording)",
	},
	{
		id: "mod_recording_toggle_p",
		kind: "key",
		concern: "mod-recording",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "P",
		modifiers: ["ctrl"],
		condition: "when recording mode active",
		detail: "Toggle recording (alternate)",
	},
	{
		id: "mod_recording_live_keys",
		kind: "key",
		concern: "mod-recording",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "A-Z/0-9",
		condition: "when recording mode active, no Ctrl/Meta",
		detail: "Play notes via keyboard layout during recording",
	},

	{
		id: "theme_jummbox_classic",
		kind: "key",
		concern: "presets",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "J",
		modifiers: ["shift", "ctrl", "alt"],
		detail: "Apply jummbox classic theme preset",
	},
	{
		id: "theme_slarmoosbox",
		kind: "key",
		concern: "presets",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "S",
		modifiers: ["shift", "ctrl", "alt"],
		detail: "Apply slarmoosbox theme preset",
	},
	{
		id: "theme_violet_verdant",
		kind: "key",
		concern: "presets",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "T",
		modifiers: ["shift", "ctrl", "alt"],
		detail: "Apply violet verdant theme preset",
	},

	{
		id: "mod_shift_down",
		kind: "key",
		concern: "editing",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Shift",
		detail: "Set patternEditor.shiftMode = true",
	},
	{
		id: "mod_shift_up",
		kind: "key",
		concern: "editing",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyUp",
		keys: "Shift",
		detail: "Set patternEditor.shiftMode = false",
	},
	{
		id: "mod_ctrl_down",
		kind: "key",
		concern: "editing",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Ctrl",
		detail: "Set patternEditor.controlMode = true",
	},
	{
		id: "mod_ctrl_up",
		kind: "key",
		concern: "editing",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyUp",
		keys: "Ctrl",
		detail: "Set patternEditor.controlMode = false",
	},

	{
		id: "prompt_close_esc",
		kind: "key",
		concern: "views",
		sourceFile: "editor/core/keyboard-handler.ts",
		handler: "handleKeyDown",
		keys: "Escape",
		condition: "when prompt is open",
		detail: "Close current prompt",
	},
];
