// Changes - Index
//
// Purpose: Barrel re-export of all editor change classes
//
// This module:
// - Re-exports note, instrument, filter, slider, song, and utility changes

// Copyright (c) 2012-2022 John Nesky and contributing authors, distributed under the MIT license, see accompanying the LICENSE.md file.

export { patternsContainSameInstruments, discardInvalidPatternInstruments, unionOfUsedNotes, generateScaleMap } from "./util";
export { ChangeMoveAndOverflowNotes, ChangePitchAdded, ChangePatternNumbers, ChangePatternsPerChannel, ChangeEnsurePatternExists, ChangePinTime, ChangePitchBend, ChangePatternRhythm, ChangeMoveNotesSideways, ChangeScale, ChangeDetectKey, ChangeValidateTrackSelection, ChangeReplacePatterns, comparePatternNotes, removeDuplicatePatterns, ChangeNoteAdded, ChangeNoteLength, ChangeNoteTruncate, ChangeRhythmNote, ChangeTranspose, ChangeTrackSelection, ChangePatternSelection, ChangeDragSelectedNotes, ChangeHoldingModRecording, ChangeDuplicateSelectedReusedPatterns, ChangePatternScale, ChangeSizeBend, ChangePaste, ChangePasteInstrument, ChangeAppendInstrument, ChangeSetPatternInstruments } from "./notes";
export { ChangeInstrumentSlider, IndexableChange, ChangePulseWidth, ChangeDecimalOffset, ChangeSupersawDynamism, ChangeSupersawSpread, ChangeSupersawShape, ChangePitchShift, ChangeDetune, ChangeRingMod, ChangeRingModHz, ChangeRingModPulseWidth, ChangeUpperLimit, ChangeLowerLimit, ChangeGranular, ChangeGrainSize, ChangeGrainAmounts, ChangeGrainRange, ChangeDistortion, ChangeBitcrusherFreq, ChangeBitcrusherQuantization, ChangePhaserMix, ChangePhaserFreq, ChangePhaserFeedback, ChangePhaserStages, ChangeStringSustain, ChangeEQFilterSimpleCut, ChangeEQFilterSimplePeak, ChangeNoteFilterSimpleCut, ChangeNoteFilterSimplePeak, ChangeEchoDelay, ChangeEchoSustain, ChangeChorus, ChangeReverb, ChangeOperatorAmplitude, ChangeFeedbackAmplitude, ChangePerEnvelopeSpeed, ChangeEnvelopeLowerBound, ChangeEnvelopeUpperBound } from "./sliders";
export { ChangeCustomizeInstrument, ChangeCustomWave, ChangeCustomAlgorythmorFeedback, ChangePreset, ChangeRandomGeneratedInstrument, ChangeTransition, ChangeToggleEffects, ChangeUnison, ChangeUnisonVoices, ChangeUnisonSpread, ChangeUnisonOffset, ChangeUnisonExpression, ChangeUnisonSign, ChangeChord, ChangeVibrato, ChangeVibratoDepth, ChangeEnvelopeSpeed, ChangeVibratoSpeed, ChangeVibratoDelay, ChangeVibratoType, ChangeArpeggioSpeed, ChangeFastTwoNoteArp, ChangeMonophonicTone, ChangeClicklessTransition, ChangeAliasing, ChangeInvertWave, ChangeSpectrum, ChangeHarmonics, ChangeDrumsetEnvelope, ChangeStringSustainType, ChangeFadeInOut, ChangeAlgorithm, ChangeFeedbackType, Change6OpAlgorithm, Change6OpFeedbackType, ChangeOperatorWaveform, ChangeOperatorPulseWidth, ChangeOperatorFrequency, ChangeChipWave, ChangeChipWaveUseAdvancedLoopControls, ChangeChipWaveLoopMode, ChangeChipWaveLoopStart, ChangeChipWaveLoopEnd, ChangeChipWaveStartOffset, ChangeChipWavePlayBackwards, ChangeNoiseWave, ChangeAddEnvelope, ChangeRemoveEnvelope, ChangeSetEnvelopeTarget, ChangeSetEnvelopeType, ChangeEnvelopePitchStart, ChangeEnvelopePitchEnd, ChangeEnvelopeInverse, ChangeDiscreteEnvelope, ChangeRandomEnvelopeSteps, ChangeRandomEnvelopeSeed, PasteEnvelope, ChangeSetEnvelopeWaveform, ChangeRingModChipWave } from "./instruments";
export { ChangeEQFilterType, ChangeNoteFilterType, ChangeSongFilterAddPoint, ChangeFilterAddPoint, FilterMoveData, ChangeSongFilterMovePoint, ChangeFilterMovePoint, ChangeSongFilterSettings, ChangeFilterSettings } from "./filters";
export { ChangeBarCount, ChangeInsertBars, ChangeDeleteBars, ChangeLimiterSettings, ChangeChannelOrder, ChangeCustomScale, ChangeChannelCount, ChangeAddChannel, ChangeRemoveChannel, ChangeChannelBar, ChangeOctave, ChangeRhythm, ChangeKey, ChangeLoop, ChangeKeyOctave, ChangeTempo, ChangeSongReverb, ChangeVolume, ChangePan, ChangePanDelay, ChangeSongTitle, ChangeChannelName, ChangeViewInstrument, ChangeInstrumentsFlags, ChangeModChannel, ChangeModInstrument, ChangeModSetting, ChangeModFilter, ChangeModEnvelope, ChangeAddChannelInstrument, ChangeRemoveChannelInstrument, ChangeSong, ChangeBeatsPerBar, pickRandomPresetValue, pickNextPresetValue, setDefaultInstruments } from "./song";
